### ISSUE TITLE
有些流地址截图和录像是花的。

### ISSUE THREAD

**Issue by yougaohui** [ILoveLin/ijkplayer_Record_PlayerAddUI#2]
比如这个地址rtmp://58.200.131.2:1935/livetv/cctv15
![image](https://user-images.githubusercontent.com/9983208/118255866-5ca5ab80-b4df-11eb-82ff-0a380bac8732.png)

**Comment by ILoveLin** [comment]
你去我github上面下载，GodPlayer项目找到         VlcPlayerActivity，用里面的VLC吧，也可以截图录像等等（支持rtsp，rtmp，http等等的直播或者转播视频的录像，截图），健壮性比ijk好很多，自己看下代码，把你用到的直接复制到新的项目里面就行，很快你就能搞好的。

**Comment by yougaohui** [comment]
好的，谢谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月15日(星期六) 上午8:24
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ILoveLin/ijkplayer_Record_PlayerAddUI] 有些流地址截图和录像是花的。 (#2)





 
你去我github上面下载，GodPlayer项目找到         VlcPlayerActivity，用里面的VLC吧，也可以截图录像等等（支持rtsp，rtmp，http等等的直播或者转播视频的录像，截图），健壮性比ijk好很多，自己看下代码，把你用到的直接复制到新的项目里面就行，很快你就能搞好的。
